name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: vn -f TourGuide/pom.xml clean install -DskipTests=false

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tourguide:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tourguide:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull and run Docker container on server
        run: |
          ssh user@server "
          docker pull ${{ secrets.DOCKER_USERNAME }}/tourguide:${{ github.sha }} &&
          docker stop tourguide || true &&
          docker rm tourguide || true &&
          docker run -d --name tourguide -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/tourguide:${{ github.sha }}"
